In [1]:
import pandas as pd
import os
import glob

In [2]:
# Change directory
results_loc = "./"#input("Enter the path for your download directory: ")
try:
    os.chdir(results_loc)
except FileNotFoundError:
    print("Please change the directory to the location of your results files")

# List all files and directories in current directory
files = glob.glob((results_loc + "/*.csv").split("/")[-1])
print(files)

['JC-201701-citibike-tripdata.csv', 'JC-201602-citibike-tripdata.csv', 'JC-201902-citibike-tripdata.csv', 'JC-201512-citibike-tripdata.csv', 'JC-201801-citibike-tripdata.csv', 'JC-201709-citibike-tripdata.csv', 'JC-201809-citibike-tripdata.csv', 'JC-201510-citibike-tripdata.csv', 'JC-201803-citibike-tripdata.csv', 'JC-201703-citibike-tripdata.csv', 'JC_combined_data.csv', 'JC-201608-citibike-tripdata.csv', 'JC-201606-citibike-tripdata.csv', 'JC-201705-citibike-tripdata.csv', 'JC-201610-citibike-tripdata.csv', 'JC-201805-citibike-tripdata.csv', 'JC-201811-citibike-tripdata.csv', 'JC-201807-citibike-tripdata.csv', 'JC-201604-citibike-tripdata.csv', 'JC-201707-citibike-tripdata.csv', 'JC-201711-citibike-tripdata.csv', 'JC-201612-citibike-tripdata.csv', 'JC-201708-citibike-tripdata.csv', 'JC-201808-citibike-tripdata.csv', 'JC-201603-citibike-tripdata.csv', 'JC-201609-citibike-tripdata.csv', 'JC-201511-citibike-tripdata.csv', 'JC-201901-citibike-tripdata.csv', 'JC-201802-citibike-tripdata.csv', 'JC-201702-citibike-tripdata.csv', 'JC-201601-citibike-tripdata.csv', 'JC-201712-citibike-tripdata.csv', 'JC-201611-citibike-tripdata.csv', 'JC-201607-citibike-tripdata.csv', 'JC-201704-citibike-tripdata.csv', 'JC-201804-citibike-tripdata.csv', 'JC-201812-citibike-tripdata.csv', 'JC-201509-citibike-tripdata.csv', 'JC-201806-citibike-tripdata.csv', 'JC-201810-citibike-tripdata.csv', 'JC-201710-citibike-tripdata.csv', 'JC-201605-citibike-tripdata.csv', 'JC-201706-citibike-tripdata.csv']

In [3]:
df = pd.DataFrame(columns=['tripduration',
'starttime',
'stoptime',
'start station id',
'start station name',
'start station latitude',
'start station longitude',
'end station id',
'end station name',
'end station latitude',
'end station longitude',
'bikeid',
'usertype',
'birth year',
'gender'])
df

Empty DataFrame
Columns: [tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []

In [4]:
file_count = 0
for item in files:

    try:
        print(f"Parsing {item}")
        quarter = item.split('-')[1]
        xl = pd.read_csv(item, names=['tripduration','starttime','stoptime','start station id','start station name',
                                      'start station latitude', 'start station longitude', 'end station id',
                                      'end station name', 'end station latitude', 'end station longitude', 'bikeid',
                                      'usertype', 'birth year', 'gender'], header=None, skiprows=[0])

        date = item.split('-')[1]
        xl["year"] = date[0:4]
        xl["month"] = date[4:7]
        print(f'{date[0:4]} and {date[4:7]}')
        df = df.append(xl, ignore_index=True, sort=False)
        file_count+=1
    except XLRDError:
        print("Close any open files and try again")
        
print(f"Parsed {file_count} files into dataframe df")

Parsing JC-201701-citibike-tripdata.csv
2017 and 01
Parsing JC-201602-citibike-tripdata.csv
2016 and 02
Parsing JC-201902-citibike-tripdata.csv
2019 and 02
Parsing JC-201512-citibike-tripdata.csv
2015 and 12
Parsing JC-201801-citibike-tripdata.csv
2018 and 01
Parsing JC-201709-citibike-tripdata.csv
2017 and 09
Parsing JC-201809-citibike-tripdata.csv
2018 and 09
Parsing JC-201510-citibike-tripdata.csv
2015 and 10
Parsing JC-201803-citibike-tripdata.csv
2018 and 03
Parsing JC-201703-citibike-tripdata.csv
2017 and 03
Parsing JC_combined_data.csv

NameError: name 'XLRDError' is not defined

In [113]:
len(df)

987528

In [115]:
df.dtypes

tripduration                object
starttime                   object
stoptime                    object
start station id            object
start station name          object
start station latitude     float64
start station longitude    float64
end station id              object
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                      object
usertype                    object
birth year                 float64
gender                      object
year                        object
month                       object
dtype: object

In [116]:
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,year,month
0,148,2017-01-01 00:21:32,2017-01-01 00:24:01,3276,Marin Light Rail,40.714584,-74.042817,3185,City Hall,40.717733,-74.043845,24575,Subscriber,1983.0,1,2017,01
1,1283,2017-01-01 00:24:35,2017-01-01 00:45:58,3183,Exchange Place,40.716247,-74.033459,3198,Heights Elevator,40.748716,-74.040443,24723,Subscriber,1978.0,1,2017,01
2,372,2017-01-01 00:38:19,2017-01-01 00:44:31,3183,Exchange Place,40.716247,-74.033459,3211,Newark Ave,40.721525,-74.046305,24620,Subscriber,1989.0,1,2017,01
3,1513,2017-01-01 00:38:37,2017-01-01 01:03:50,3194,McGinley Square,40.725340,-74.067622,3271,Danforth Light Rail,40.692640,-74.088012,24668,Subscriber,1961.0,1,2017,01
4,639,2017-01-01 01:47:52,2017-01-01 01:58:31,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,26167,Subscriber,1993.0,1,2017,01

In [117]:
dfg = df.groupby(['year','month'])['bikeid'].count()

In [118]:
dfg

year  month
2015  09        6668
      10       19264
      11       15113
      12       11838
2016  01        7479
      02        8250
      03       13511
      04       16342
      05       19488
      06       23947
      07       24436
      08       34149
      09       33425
      10       29611
      11       21832
      12       15114
2017  01       12926
      02       14026
      03       12201
      04       21186
      05       25966
      06       32060
      07       33573
      08       35472
      09       33119
      10       34919
      11       23582
      12       15898
2018  01       12677
      02       15104
      03       17109
      04       23634
      05       34456
      06       40937
      07       42268
      08       44432
      09       39022
      10       39138
      11       24910
      12       20205
2019  01       19676
      02       18565
Name: bikeid, dtype: int64

In [119]:
len(df['bikeid'].unique())

1631

In [5]:
# df = pd.read_csv('JC_combined_data.csv')

In [6]:
df.describe()

,Unnamed: 0,tripduration,start station id,start station latitude,start station longitude,end station id,end station latitude,end station longitude,bikeid,birth year,gender,year,month
count,987528.000000,9.875280e+05,987528.000000,987528.000000,987528.000000,987528.000000,987528.000000,987528.000000,987528.000000,943286.000000,987528.000000,987528.000000,987528.000000
mean,493763.500000,7.891229e+02,3234.438291,40.722773,-74.046163,3229.795884,40.689944,-73.986743,27669.723058,1979.930751,1.138627,2017.077997,7.158510
std,285074.922655,2.941728e+04,98.503018,0.007651,0.010850,114.694701,1.147702,2.086858,2823.687367,10.054295,0.509325,0.985946,3.107812
min,0.000000,6.100000e+01,3183.000000,40.692640,-74.096937,79.000000,0.000000,-74.096937,14529.000000,1887.000000,0.000000,2015.000000,1.000000
25%,246881.750000,2.350000e+02,3187.000000,40.717732,-74.050444,3186.000000,40.716540,-74.049968,24694.000000,1974.000000,1.000000,2016.000000,5.000000
50%,493763.500000,3.520000e+02,3203.000000,40.721525,-74.043845,3202.000000,40.719586,-74.043117,26298.000000,1982.000000,1.000000,2017.000000,8.000000
75%,740645.250000,5.950000e+02,3225.000000,40.727224,-74.038051,3214.000000,40.727224,-74.038051,29553.000000,1988.000000,1.000000,2018.000000,10.000000
max,987527.000000,2.026021e+07,3694.000000,40.752559,-74.032108,3709.000000,40.814326,0.000000,35652.000000,2002.000000,2.000000,2019.000000,12.000000

In [9]:
df = df.loc[df['end station longitude']!=0]
df

,Unnamed: 0,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,year,month
0,0,148,2017-01-01 00:21:32,2017-01-01 00:24:01,3276,Marin Light Rail,40.714584,-74.042817,3185,City Hall,40.717732,-74.043845,24575,Subscriber,1983.0,1,2017,1
1,1,1283,2017-01-01 00:24:35,2017-01-01 00:45:58,3183,Exchange Place,40.716247,-74.033459,3198,Heights Elevator,40.748716,-74.040443,24723,Subscriber,1978.0,1,2017,1
2,2,372,2017-01-01 00:38:19,2017-01-01 00:44:31,3183,Exchange Place,40.716247,-74.033459,3211,Newark Ave,40.721525,-74.046305,24620,Subscriber,1989.0,1,2017,1
3,3,1513,2017-01-01 00:38:37,2017-01-01 01:03:50,3194,McGinley Square,40.725340,-74.067622,3271,Danforth Light Rail,40.692640,-74.088012,24668,Subscriber,1961.0,1,2017,1
4,4,639,2017-01-01 01:47:52,2017-01-01 01:58:31,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,26167,Subscriber,1993.0,1,2017,1
5,5,258,2017-01-01 01:56:29,2017-01-01 02:00:48,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,24604,Subscriber,1970.0,1,2017,1
6,6,663,2017-01-01 02:12:34,2017-01-01 02:23:38,3270,Jersey & 6th St,40.725289,-74.045572,3206,Hilltop,40.731169,-74.057574,24641,Subscriber,1978.0,1,2017,1
7,7,567,2017-01-01 02:15:52,2017-01-01 02:25:20,3192,Liberty Light Rail,40.711242,-74.055701,3213,Van Vorst Park,40.718489,-74.047727,24513,Subscriber,1970.0,1,2017,1
8,8,551,2017-01-01 02:16:03,2017-01-01 02:25:15,3192,Liberty Light Rail,40.711242,-74.055701,3213,Van Vorst Park,40.718489,-74.047727,24463,Subscriber,1967.0,2,2017,1
9,9,573,2017-01-01 02:22:17,2017-01-01 02:31:50,3212,Christ Hospital,40.734786,-74.050444,3225,Baldwin at Montgomery,40.723659,-74.064194,24486,Subscriber,1984.0,1,2017,1
10,10,535,2017-01-01 02:22:59,2017-01-01 02:31:55,3212,Christ Hospital,40.734786,-74.050444,3225,Baldwin at Montgomery,40.723659,-74.064194,24520,Subscriber,1987.0,2,2017,1
11,11,224,2017-01-01 02:23:53,2017-01-01 02:27:37,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,24512,Subscriber,1984.0,2,2017,1
12,12,1699,2017-01-01 02:33:12,2017-01-01 03:01:31,3213,Van Vorst Park,40.718489,-74.047727,3202,Newport PATH,40.727224,-74.033759,24513,Subscriber,1985.0,1,2017,1
13,13,350,2017-01-01 02:37:31,2017-01-01 02:43:22,3186,Grove St PATH,40.719586,-74.043117,3209,Brunswick St,40.724176,-74.050656,24409,Subscriber,1964.0,2,2017,1
14,14,346,2017-01-01 03:09:09,2017-01-01 03:14:56,3202,Newport PATH,40.727224,-74.033759,3186,Grove St PATH,40.719586,-74.043117,24513,Subscriber,1985.0,1,2017,1
15,15,367,2017-01-01 03:16:35,2017-01-01 03:22:42,3187,Warren St,40.721124,-74.038051,3267,Morris Canal,40.712419,-74.038526,24699,Subscriber,1989.0,1,2017,1
16,16,148,2017-01-01 03:24:02,2017-01-01 03:26:30,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24513,Subscriber,1985.0,1,2017,1
17,17,204,2017-01-01 03:52:29,2017-01-01 03:55:53,3203,Hamilton Park,40.727596,-74.044247,3213,Van Vorst Park,40.718489,-74.047727,24442,Subscriber,1986.0,1,2017,1
18,18,33726,2017-01-01 04:35:14,2017-01-01 13:57:20,3275,Columbus Drive,40.718355,-74.038914,3186,Grove St PATH,40.719586,-74.043117,26281,Customer,NaN,0,2017,1
19,19,591,2017-01-01 04:35:36,2017-01-01 04:45:27,3275,Columbus Drive,40.718355,-74.038914,3186,Grove St PATH,40.719586,-74.043117,26194,Customer,NaN,0,2017,1
20,20,454,2017-01-01 05:17:42,2017-01-01 05:25:16,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,24555,Subscriber,1972.0,2,2017,1
21,21,217,2017-01-01 05:25:35,2017-01-01 05:29:13,3195,Sip Ave,40.730743,-74.063784,3225,Baldwin at Montgomery,40.723659,-74.064194,24408,Subscriber,1987.0,1,2017,1
22,22,107,2017-01-01 06:29:15,2017-01-01 06:31:03,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,24681,Subscriber,1964.0,1,2017,1
23,23,453,2017-01-01 07:08:01,2017-01-01 07:15:34,3195,Sip Ave,40.730743,-74.063784,3193,Lincoln Park,40.724605,-74.078406,26163,Subscriber,1983.0,1,2017,1
24,24,447,2017-01-01 07:12:53,2017-01-01 07:20:20,3195,Sip Ave,40.730743,-74.063784,3193,Lincoln Park,40.724605,-74.078406,26431,Subscriber,1986.0,1,2017,1
25,25,730,2017-01-01 07:38:57,2017-01-01 07:51:08,3281,Leonard Gordon Park,40.745910,-74.057271,3195,Sip Ave,40.730743,-74.063784,24495,Subscriber,1962.0,1,2017,1
26,26,435,2017-01-01 07:55:19,2017-01-01 08:02:35,3192,Liberty Light Rail,40.711242,-74.055701,3186,Grove St PATH,40.719586,-74.043117,24390,Subscriber,1986.0,1,2017,1
27,27,458,2017-01-01 08:16:36,2017-01-01 08:24:15,3195,Sip Ave,40.730743,-74.063784,3280,Astor Place,40.719282,-74.071262,26255,Subscriber,1992.0,1,2017,1
28,28,258,2017-01-01 08:24:36,2017-01-01 08:28:54,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,26308,Subscriber,1977.0,1,2017,1
29,29,537,2017-01-01 08:56:28,2017-01-01 09:05:26,3196,Riverview Park,40.744319,-74.043991,3210,Pershing Field,40.742677,-74.051789,26234,Subscriber,1983.0,1,2017,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987498,987498,712,2017-06-30 22:43:39,2017-06-30 22:55:31,3199,Newport Pkwy,40.728745,-74.032108,3186,Grove St PATH,40.719586,-74.043117,29226,Subscriber,1984.0,1,2017,6
987499,987499,243,2017-06-30 22:44:15,2017-06-30 22:48:19,3273,Manila & 1st,40.721651,-74.042884,3203,Hamilton Park,40.727596,-74.044247,29572,Subscriber,1982.0,1,2017,6
987500,987500,390,2017-06-30 22:44:16,2017-06-30 22:50:46,3199,Newport Pkwy,40.728745,-74.032108,3183,Exchange Place,40.716247,-74.033459,29297,Subscriber,1993.0,1,2017,6
987501,987501,280,2017-06-30 22:46:38,2017-06-30 22:51:18,3187,Warren St,40.721124,-74.038051,3267,Morris Canal,40.712419,-74.038526,29447,Subscriber,1983.0,1,2017,6
987502,987502,213,2017-06-30 22:52:23,2017-06-30 22:55:57,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29578,Subscriber,1993.0,1,2017,6
987503,987503,225,2017-06-30 22:52:37,2017-06-30 22:56:23,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26254,Subscriber,1977.0,1,2017,6
987504,987504,548,2017-06-30 22:52:40,2017-06-30 23:01:49,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,26270,Subscriber,1986.0,1,2017,6
987505,987505,228,2017-06-30 22:54:02,2017-06-30 22:57:50,3186,Grove St PATH,40.719586,-74.043117,3209,Brunswick St,40.724176,-74.050656,29597,Subscriber,1989.0,1,2017,6
987506,987506,249,2017-06-30 23:01:10,2017-06-30 23:05:20,3276,Marin Light Rail,40.714584,-74.042817,3213,Van Vorst Park,40.718489,-74.047727,26173,Subscriber,1989.0,2,2017,6
987507,987507,134,2017-06-30 23:01:57,2017-06-30 23:04:12,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,29580,Subscriber,1992.0,1,2017,6
987508,987508,444,2017-06-30 23:03:20,2017-06-30 23:10:44,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,26272,Subscriber,1966.0,1,2017,6
987509,987509,360,2017-06-30 23:03:27,2017-06-30 23:09:28,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,29226,Subscriber,1963.0,1,2017,6
987510,987510,304,2017-06-30 23:06:20,2017-06-30 23:11:24,3275,Columbus Drive,40.718355,-74.038914,3199,Newport Pkwy,40.728745,-74.032108,26183,Subscriber,1965.0,1,2017,6
987511,987511,859,2017-06-30 23:08:00,2017-06-30 23:22:19,3183,Exchange Place,40.716247,-74.033459,3275,Columbus Drive,40.718355,-74.038914,29498,Subscriber,1966.0,1,2017,6
987512,987512,252,2017-06-30 23:08:31,2017-06-30 23:12:44,3211,Newark Ave,40.721525,-74.046305,3203,Hamilton Park,40.727596,-74.044247,29253,Subscriber,1984.0,1,2017,6
987513,987513,241,2017-06-30 23:08:42,2017-06-30 23:12:44,3211,Newark Ave,40.721525,-74.046305,3203,Hamilton Park,40.727596,-74.044247,29601,Subscriber,NaN,0,2017,6
987514,987514,406,2017-06-30 23:09:30,2017-06-30 23:16:17,3195,Sip Ave,40.730743,-74.063784,3280,Astor Place,40.719282,-74.071262,29618,Subscriber,1964.0,1,2017,6
987515,987515,191,2017-06-30 23:09:55,2017-06-30 23:13:06,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,29298,Subscriber,1970.0,1,2017,6
987516,987516,470,2017-06-30 23:19:46,2017-06-30 23:27:37,3275,Columbus Drive,40.718355,-74.038914,3279,Dixon Mills,40.721630,-74.049968,29635,Subscriber,1990.0,2,2017,6
987517,987517,2436,2017-06-30 23:22:43,2017-07-01 00:03:19,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,26170,Subscriber,1975.0,1,2017,6
987518,987518,224,2017-06-30 23:23:07,2017-06-30 23:26:52,3272,Jersey & 3rd,40.723332,-74.045953,3209,Brunswick St,40.724176,-74.050656,29277,Subscriber,1985.0,1,2017,6
987519,987519,528,2017-06-30 23:23:43,2017-06-30 23:32:32,3213,Van Vorst Park,40.718489,-74.047727,3194,McGinley Square,40.725340,-74.067622,29503,Subscriber,1970.0,1,2017,6
987520,987520,893,2017-06-30 23:26:37,2017-06-30 23:41:30,3186,Grove St PATH,40.719586,-74.043117,3194,McGinley Square,40.725340,-74.067622,26255,Subscriber,1987.0,1,2017,6
987521,987521,240,2017-06-30 23:31:25,2017-06-30 23:35:25,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29674,Subscriber,1992.0,2,2017,6
987522,987522,250,2017-06-30 23:49:22,2017-06-30 23:53:33,3203,Hamilton Park,40.727596,-74.044247,3211,Newark Ave,40.721525,-74.046305,29526,Subscriber,1956.0,2,2017,6
987523,987523,934,2017-06-30 23:50:05,2017-07-01 00:05:40,3211,Newark Ave,40.721525,-74.046305,3207,Oakland Ave,40.737604,-74.052478,26287,Subscriber,1991.0,1,2017,6
987524,987524,908,2017-06-30 23:50:31,2017-07-01 00:05:39,3211,Newark Ave,40.721525,-74.046305,3207,Oakland Ave,40.737604,-74.052478,29472,Subscriber,1993.0,2,2017,6
987525,987525,238,2017-06-30 23:52:16,2017-06-30 23:56:15,3203,Hamilton Park,40.727596,-74.044247,3211,Newark Ave,40.721525,-74.046305,29572,Subscriber,1992.0,1,2017,6
987526,987526,184,2017-06-30 23:57:50,2017-07-01 00:00:54,3267,Morris Canal,40.712419,-74.038526,3183,Exchange Place,40.716247,-74.033459,29199,Subscriber,1985.0,1,2017,6
987527,987527,463,2017-06-30 23:59:16,2017-07-01 00:07:00,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,26289,Subscriber,1965.0,1,2017,6

In [10]:
df.to_csv('JC_combined_data.csv')